global using BlazingPizza.BussinesObjects.Agregates;
global using BlazingPizza.BussinesObjects.Entities;
global using BlazingPizza.BussinesObjects.Interfaces.Checkout;
global using BlazingPizza.BussinesObjects.Interfaces.Common;
global using BlazingPizza.BussinesObjects.Interfaces.ConfigurePizzaDialog;
global using BlazingPizza.BussinesObjects.Interfaces.Index;
global using BlazingPizza.BussinesObjects.Interfaces.OrderDetails;
global using BlazingPizza.BussinesObjects.Interfaces.Specials;
global using Microsoft.AspNetCore.Components;
