global using BlazingPizza.EFCore.Repositories.DataContext;
global using BlazingPizza.EFCore.Repositories.Entities;
global using BlazingPizza.EFCore.Repositories.Mappers;
global using BlazingPizza.BussinesObjects.Interfaces.Common;
global using Microsoft.EntityFrameworkCore;
global using Microsoft.EntityFrameworkCore.Design;
global using Microsoft.EntityFrameworkCore.Metadata.Builders;
global using Microsoft.Extensions.DependencyInjection;
global using System.Reflection;
global using BlazingPizza.BussinesObjects.Dtos;
global using EFEntities = BlazingPizza.EFCore.Repositories.Entities;
