global using BlazingPizza.EFCore.Repositories.DataContext;
global using BlazingPizza.EFCore.Repositories.Entities;
global using BlazingPizza.EFCore.Repositories.Mappers;
global using BlazingPizza.Backend.BussinesObjects.Interfaces.Common;
global using Microsoft.EntityFrameworkCore;
global using Microsoft.EntityFrameworkCore.Design;
global using Microsoft.EntityFrameworkCore.Metadata.Builders;
global using Microsoft.Extensions.DependencyInjection;
global using System.Reflection;
global using EFEntities = BlazingPizza.EFCore.Repositories.Entities;
global using BlazingPizza.Backend.BussinesObjects.ValueObjects.Options;
global using Microsoft.Extensions.Options;
global using BlazingPizza.EFCore.Repositories.Interfaces;
global using BlazingPizza.Shared.BussinesObjects.Dtos;
global using BlazingPizza.Shared.BussinesObjects.Enums;
