global using BlazingPizza.Gateways;
global using BlazingPizza.Models;
global using BlazingPizza.ViewModels;
global using Microsoft.Extensions.DependencyInjection;
global using Microsoft.Extensions.Options;
global using BlazingPizza.FrondEnd.BussinesObjects.ValueObjects.Options;
global using BlazingPizza.Shared.Validators;
global using Toast.Blazor;
global using SweetAlert.Blazor;
