global using BlazingPizza.FrondEnd.BussinesObjects.ValueObjects.Options;
global using BlazingPizza.IoC.Frontend;
global using BlazingPizza.Razor.Views.Shared;
global using Microsoft.AspNetCore.Components.Web;
global using Microsoft.AspNetCore.Components.WebAssembly.Hosting;
global using Microsoft.Extensions.DependencyInjection;
global using Microsoft.Extensions.Options;
global using Membership.Blazor.IoC;
global using Membership.Blazor.WebApiGateway;
