global using BlazingPizza.Shared.BussinesObjects.Entities;
global using BlazingPizza.Backend.BussinesObjects.Interfaces.Common;
global using BlazingPizza.Backend.BussinesObjects.Interfaces.GetSpecials;
global using Microsoft.Extensions.DependencyInjection;
global using BlazingPizza.Backend.BussinesObjects.Interfaces.GetToppings;
global using BlazingPizza.Backend.BussinesObjects.Interfaces.PlaceOrder;
global using BlazingPizza.Backend.BussinesObjects.Interfaces.GetOrders;
global using BlazingPizza.Backend.BussinesObjects.Interfaces.GetOrder;
global using BlazingPizza.Shared.BussinesObjects.Dtos;
